//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tbl_QLHieuThuocEntities : DbContext
    {
        public tbl_QLHieuThuocEntities()
            : base("name=tbl_QLHieuThuocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_CHITIETHANGHOA> tbl_CHITIETHANGHOA { get; set; }
        public virtual DbSet<tbl_CTHOADON> tbl_CTHOADON { get; set; }
        public virtual DbSet<tbl_CTPHIEUNHAP> tbl_CTPHIEUNHAP { get; set; }
        public virtual DbSet<tbl_DUOCSI> tbl_DUOCSI { get; set; }
        public virtual DbSet<tbl_HOADON> tbl_HOADON { get; set; }
        public virtual DbSet<tbl_KHACHHANG> tbl_KHACHHANG { get; set; }
        public virtual DbSet<tbl_KHO> tbl_KHO { get; set; }
        public virtual DbSet<tbl_LOAI> tbl_LOAI { get; set; }
        public virtual DbSet<tbl_NGUOIDUNG> tbl_NGUOIDUNG { get; set; }
        public virtual DbSet<tbl_NHACUNGCAP> tbl_NHACUNGCAP { get; set; }
        public virtual DbSet<tbl_NHASANXUAT> tbl_NHASANXUAT { get; set; }
        public virtual DbSet<tbl_PHIEUNHAP> tbl_PHIEUNHAP { get; set; }
        public virtual DbSet<tbl_SANPHAM> tbl_SANPHAM { get; set; }
    }
}
