//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CTPHIEUNHAP
    {
        public string MaCTPN { get; set; }
        public string MaPN { get; set; }
        public string MACTSP { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual tbl_CHITIETHANGHOA tbl_CHITIETHANGHOA { get; set; }
        public virtual tbl_PHIEUNHAP tbl_PHIEUNHAP { get; set; }
    }
}
