//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SANPHAM()
        {
            this.tbl_CHITIETHANGHOA = new HashSet<tbl_CHITIETHANGHOA>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string ThanhPhan { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public byte[] HinhAnh { get; set; }
        public Nullable<double> Gia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CHITIETHANGHOA> tbl_CHITIETHANGHOA { get; set; }
        public virtual tbl_LOAI tbl_LOAI { get; set; }
        public virtual tbl_NHASANXUAT tbl_NHASANXUAT { get; set; }
    }
}
