//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_HOADON()
        {
            this.tbl_CTHOADON = new HashSet<tbl_CTHOADON>();
        }
    
        public string MaHD { get; set; }
        public int MaDuocSi { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CTHOADON> tbl_CTHOADON { get; set; }
        public virtual tbl_DUOCSI tbl_DUOCSI { get; set; }
        public virtual tbl_KHACHHANG tbl_KHACHHANG { get; set; }
    }
}
