//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CHITIETHANGHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CHITIETHANGHOA()
        {
            this.tbl_CTHOADON = new HashSet<tbl_CTHOADON>();
            this.tbl_CTPHIEUNHAP = new HashSet<tbl_CTPHIEUNHAP>();
        }
    
        public string MACTSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> HSD { get; set; }
        public Nullable<System.DateTime> NSX { get; set; }
        public Nullable<int> MASP { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string MaKho { get; set; }
    
        public virtual tbl_KHO tbl_KHO { get; set; }
        public virtual tbl_SANPHAM tbl_SANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CTHOADON> tbl_CTHOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CTPHIEUNHAP> tbl_CTPHIEUNHAP { get; set; }
    }
}
