//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CTHOADON
    {
        public string MaHD { get; set; }
        public string MaCTSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string MaCTHD { get; set; }
    
        public virtual tbl_CHITIETHANGHOA tbl_CHITIETHANGHOA { get; set; }
        public virtual tbl_HOADON tbl_HOADON { get; set; }
    }
}
