//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PHIEUNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PHIEUNHAP()
        {
            this.tbl_CTPHIEUNHAP = new HashSet<tbl_CTPHIEUNHAP>();
        }
    
        public string MaPN { get; set; }
        public int MaDuocSi { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<System.DateTime> NgayNhapHang { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public string MaKho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CTPHIEUNHAP> tbl_CTPHIEUNHAP { get; set; }
        public virtual tbl_DUOCSI tbl_DUOCSI { get; set; }
        public virtual tbl_KHO tbl_KHO { get; set; }
        public virtual tbl_NHACUNGCAP tbl_NHACUNGCAP { get; set; }
    }
}
