//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_KHO()
        {
            this.tbl_CHITIETHANGHOA = new HashSet<tbl_CHITIETHANGHOA>();
            this.tbl_PHIEUNHAP = new HashSet<tbl_PHIEUNHAP>();
        }
    
        public string MaKho { get; set; }
        public string ViTri { get; set; }
        public string TenKho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CHITIETHANGHOA> tbl_CHITIETHANGHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PHIEUNHAP> tbl_PHIEUNHAP { get; set; }
    }
}
